# Generated by Django 3.1.3 on 2025-12-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('display_price', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('features', models.JSONField(default=list)),
                ('sizes', models.JSONField(default=list)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
